### ISSUE TITLE
no output?

### ISSUE THREAD

**Issue by Bra1nsen** [fsteinhardt/sds011#1]
hey dude i get no data.. did it rlly work?

**Comment by fsteinhardt** [comment]
I don't remember if I used this. But this is only a slightly modified copy of 

https://gist.github.com/jon1012/9409e50287343a5ab5d3a451b5e4a515/93e93d8f0d038a2793fb01a643dd47ece187d690

and from the comments there it looks like it is able to read data.

**Comment by Bra1nsen** [comment]
thanks for reply, did you install drivers for usb connection? or did you just plug in and run the python code? -thanks

**Comment by Bra1nsen** [comment]
bro i dont get any data -.-
the sensor works with c code but not with the python snippet..

![nodata](https://user-images.githubusercontent.com/58213050/185980885-ffb13590-913f-4f21-91ae-8890ffbf557d.PNG)

**Comment by Bra1nsen** [comment]
https://github.com/MatejKovacic/SDS011-SDS018-and-SDS021-dust-sensors-reader 

this one worked =)
